import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Url } from "./url.enums"

@Injectable({
  providedIn: 'root'
})
export class ApisService {

  private API_URL = Url.WebPortal;
  constructor(private httpClient: HttpClient) { }

  private performGetRequest(url: string, params?: any): Observable<any> {
    return this.httpClient.get(url, { params });
  }

  private performPostRequest(url: string, body?: any): Observable<any> {
    return this.httpClient.post(url, body, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  }

  private performPostRequestMollie(url: string, body?: any): Observable<any> {
    return this.httpClient.post(url, body, {
      headers: {
        'Content-Type': 'application/json',
      },
      responseType: 'text',
    });
  }

  getCountries(): Observable<any> {
    return this.performGetRequest(`${this.API_URL}system/countries`);
  }

  imeiValidation(imei: string): Observable<any> {
    return this.performGetRequest(`${this.API_URL}system/status/${imei}`);
  }

  vatValidation(vatNumber: string, countryCode: string): Observable<any> {
    return this.performGetRequest(`https://test-my.we.stream/vies-api/?countryCode=${countryCode}&vatNumber=${vatNumber}`);
  }

  getBundles(imei: string, accountInfo: any, referralCode: any): Observable<any> {
    const dummyAccountInfo = {
      "accountType": '',
      "imei": '',
      "imei-valid-value": '',
      "firstName": '',
      "lastName": '',
      "email": "",
      "countryOfOrigin": '',
      "pCity": '',
      "pAddress": "",
      "pPostal": '',
      "sameAsPermanent": '',
      "rCity": '',
      "rAddress": "",
      "rPostal": '',
      "confirmInfo": '',
      "bankCountry": '',
      "rCountry": '',
      "pCountry": '',
      "countryName": ''
    };

    const url = `${this.API_URL}user/bundles?country=ALL&imei=${imei}&referralCode=${referralCode}`;
    return this.performPostRequest(url, accountInfo || JSON.stringify(dummyAccountInfo));
  }

  getOverviewCountries() {
    return [
      { "name": "Albania" },
      { "name": "Algeria" },
      { "name": "Anguilla" },
      { "name": "Antigua and Barbuda" },
      { "name": "Argentina" },
      { "name": "Armenia" },
      { "name": "Aruba" },
      { "name": "Australia" },
      { "name": "Austria" },
      { "name": "Azerbaijan" },
      { "name": "Bahamas" },
      { "name": "Bahrain" },
      { "name": "Bangladesh" },
      { "name": "Barbados" },
      { "name": "Belarus" },
      { "name": "Belgium" },
      { "name": "Bermuda" },
      { "name": "Bonaire" },
      { "name": "Bosnia & Herzegovina " },
      { "name": "Brazil" },
      { "name": "British Virgin Islands" },
      { "name": "Brunei" },
      { "name": "Bulgaria" },
      { "name": "Cambodia" },
      { "name": "Canada" },
      { "name": "Cayman Islands" },
      { "name": "Chad" },
      { "name": "Chile" },
      { "name": "China" },
      { "name": "Colombia" },
      { "name": "Congo Dem. Rep." },
      { "name": "Costa Rica" },
      { "name": "Croatia" },
      { "name": "Curacao" },
      { "name": "Cyprus" },
      { "name": "Czech Republic" },
      { "name": "Denmark" },
      { "name": "Desirade" },
      { "name": "Dominica" },
      { "name": "Dominican Republic" },
      { "name": "Ecuador" },
      { "name": "Egypt" },
      { "name": "El Salvador" },
      { "name": "Estonia" },
      { "name": "Faroe Islands" },
      { "name": "Fiji" },
      { "name": "Finland" },
      { "name": "France" },
      { "name": "French Guyana" },
      { "name": "Georgia" },
      { "name": "Germany" },
      { "name": "Ghana" },
      { "name": "Gibraltar" },
      { "name": "Greece" },
      { "name": "Grenada" },
      { "name": "Guadeloupe" },
      { "name": "Guam" },
      { "name": "Guatemala" },
      { "name": "Guernsey" },
      { "name": "Guyana" },
      { "name": "Haiti" },
      { "name": "Honduras" },
      { "name": "Hong Kong" },
      { "name": "Hungary" },
      { "name": "Iceland" },
      { "name": "India" },
      { "name": "Indonesia" },
      { "name": "Ireland" },
      { "name": "Isle of Man" },
      { "name": "Israel" },
      { "name": "Italy" },
      { "name": "Jamaica" },
      { "name": "Japan" },
      { "name": "Jersey" },
      { "name": "Kazakhstan" },
      { "name": "Kenya" },
      { "name": "Korea" },
      { "name": "Kuwait" },
      { "name": "Kyrgyzstan" },
      { "name": "Laos" },
      { "name": "Latvia" },
      { "name": "Liechtenstein" },
      { "name": "Lithuania" },
      { "name": "Luxembourg" },
      { "name": "Macao" },
      { "name": "Macedonia" },
      { "name": "Madagascar" },
      { "name": "Malaysia" },
      { "name": "Malta" },
      { "name": "Marie-Galante" },
      { "name": "Martinique" },
      { "name": "Mauritius" },
      { "name": "Mexico" },
      { "name": "Moldova" },
      { "name": "Mongolia" },
      { "name": "Montenegro" },
      { "name": "Montserrat" },
      { "name": "Morocco" },
      { "name": "Myanmar" },
      { "name": "Nepal" },
      { "name": "Netherlands" },
      { "name": "New Zealand" },
      { "name": "Nicaragua" },
      { "name": "Nigeria" },
      { "name": "Norway" },
      { "name": "Oman" },
      { "name": "Pakistan" },
      { "name": "Panama" },
      { "name": "Paraguay" },
      { "name": "Peru" },
      { "name": "Philippines" },
      { "name": "Poland" },
      { "name": "Portugal" },
      { "name": "Puerto Rico" },
      { "name": "Qatar" },
      { "name": "Reunion" },
      { "name": "Romania" },
      { "name": "Russia" },
      { "name": "Saint Barthelemy" },
      { "name": "Saint Kitts & Nevis" },
      { "name": "Saint Lucia" },
      { "name": "Saint Martin" },
      { "name": "Saint Vincent and the Grenadines " },
      { "name": "Saintes" },
      { "name": "Saipan" },
      { "name": "Saudi Arabia" },
      { "name": "Serbia" },
      { "name": "Singapore" },
      { "name": "Slovakia" },
      { "name": "Slovenia" },
      { "name": "South Africa" },
      { "name": "Spain" },
      { "name": "Sri Lanka" },
      { "name": "Surinam" },
      { "name": "Sweden" },
      { "name": "Switzerland" },
      { "name": "Taiwan" },
      { "name": "Tajikistan" },
      { "name": "Tanzania" },
      { "name": "Thailand" },
      { "name": "Trinidad & Tobago" },
      { "name": "Tunisia" },
      { "name": "Turkey" },
      { "name": "Turks and Caicos Islands" },
      { "name": "Ukraine" },
      { "name": "United Arab Emirates" },
      { "name": "United Kingdom" },
      { "name": "United States" },
      { "name": "Uruguay" },
      { "name": "Uzbekistan" },
      { "name": "Venezuela" },
      { "name": "Vietnam" },
      { "name": "Zambia" }
    ]
  }

  payPaypal(code: string, params: any): Observable<any> {
    const url = `${this.API_URL}user/bundles/${code}?country=CWS&${new URLSearchParams(params).toString()}`;
    return this.performPostRequest(url, null);
  }

  payCreditCard(params: any, accountData: any): Observable<any> {
    if (params.ait) {
      accountData = {
        "accountType": '',
        "imei": '',
        "imei-valid-value": '',
        "firstName": '',
        "lastName": '',
        "email": "",
        "countryOfOrigin": '',
        "pCity": '',
        "pAddress": "",
        "pPostal": '',
        "sameAsPermanent": '',
        "rCity": '',
        "rAddress": "",
        "rPostal": '',
        "confirmInfo": '',
        "bankCountry": '',
        "rCountry": '',
        "pCountry": '',
        "countryName": ''
      };
    } else {
      params.ait = 'NA';
    }

    const url = `${this.API_URL}payment?${new URLSearchParams(params).toString()}`;
    console.log(url)
    return this.performPostRequestMollie(url, JSON.stringify(accountData));
  }

  directPurchase(params: any, accountData: any): Observable<any> {
    if (params.ait) {
      accountData = {
        "accountType": '',
        "imei": '',
        "imei-valid-value": '',
        "firstName": '',
        "lastName": '',
        "email": "",
        "countryOfOrigin": '',
        "pCity": '',
        "pAddress": "",
        "pPostal": '',
        "sameAsPermanent": '',
        "rCity": '',
        "rAddress": "",
        "rPostal": '',
        "confirmInfo": '',
        "bankCountry": '',
        "rCountry": '',
        "pCountry": '',
        "countryName": ''
      };
    }

    const url = `${this.API_URL}payment?${new URLSearchParams(params).toString()}`;
    return this.performPostRequest(url, JSON.stringify(accountData));
  }

  verifyCreditCardPayment(orderId: string, imei: any): Observable<any> {
    const params = {
      orderId: orderId,
      imei: imei
    };

    const url = `${this.API_URL}payment_callback?${new URLSearchParams(params).toString()}`;
    return this.performPostRequestMollie(url, null);
  }

  // Removed
  saveAccount(accountData: any): Observable<any> {
    return this.performPostRequest(`${this.API_URL}user/account/save`, JSON.stringify(accountData));
  }

  getAccountInfoFromToken(ait: string): Observable<any> {
    return this.performGetRequest(`${this.API_URL}user/ait?tokenValue=${ait}`);
  }

  topUpKLM(imei: string, email: string): Observable<any> {
    const data = {
      imei: imei,
      email: email
    };
    return this.performPostRequest(`${this.API_URL}payment/klm-initial`, JSON.stringify(data));
  }

  topUpFlyingBlue(imei: string, email: string): Observable<any> {
    const data = {
      imei: imei,
      email: email
    };
    return this.performPostRequest(`${this.API_URL}payment/flying-blue-initial`, JSON.stringify(data));
  }

  topUpLengers(imei: string, email: string): Observable<any> {
    const data = {
      imei: imei,
      email: email
    };
    return this.performPostRequest(`${this.API_URL}payment/lengers-initial`, JSON.stringify(data));
  }

  initPaypalPayment(accountData: any, bundle: any, ait: any): Observable<any> {
    let params = `imei=${accountData.imei || bundle.imei}&dataPlan=${bundle.dataPlan}&bundleCode=${bundle.code}&currency=${bundle.currency}`;

    if (ait) {
      params += `&ait=${ait}`;
      accountData = {
        "accountType": '',
        "imei": '',
        "imei-valid-value": '',
        "firstName": '',
        "lastName": '',
        "email": "",
        "countryOfOrigin": '',
        "pCity": '',
        "pAddress": "",
        "pPostal": '',
        "sameAsPermanent": '',
        "rCity": '',
        "rAddress": "",
        "rPostal": '',
        "confirmInfo": '',
        "bankCountry": '',
        "rCountry": '',
        "pCountry": '',
        "countryName": ''
      };
    } else {
      params += '&ait=NA';
    }

    return this.performPostRequest(`${this.API_URL}payment/paypal/init-payment?${params}`, JSON.stringify(accountData));
  }

  getLocation(): Observable<any> {
    const countryToContinentMap: { [key: string]: string } = {
      "Afghanistan": "Asia",
      "Aland Islands": "Europe",
      "Albania": "Europe",
      "Algeria": "Africa",
      "Andorra": "Europe",
      "Angola": "Africa",
      "Anguilla": "North America",
      "Antigua and Barbuda": "North America",
      "Argentina": "South America",
      "Armenia": "Europe",
      "Aruba": "North America",
      "Australia": "Oceania",
      "Austria": "Europe",
      "Azerbaijan": "Europe",
      "Bahamas": "North America",
      "Bahamas, The": "North America",
      "Bahrain": "Asia",
      "Bangladesh": "Asia",
      "Barbados": "North America",
      "Belarus": "Europe",
      "Belgium": "Europe",
      "Belize": "North America",
      "Benin": "Africa",
      "Bermuda": "North America",
      "Bhutan": "Asia",
      "Bolivia": "South America",
      "Bosnia and Herzegovina": "Europe",
      "Botswana": "Africa",
      "Bouvet Island": "South America",
      "Brazil": "South America",
      "British Indian Ocean Territory": "Asia",
      "British Virgin Islands": "North America",
      "Brunei": "Asia",
      "Bulgaria": "Europe",
      "Burkina": "Africa",
      "Burkina Faso": "Africa",
      "Burma": "Asia",
      "Burma (Myanmar)": "Asia",
      "Burundi": "Africa",
      "Cambodia": "Asia",
      "Cameroon": "Africa",
      "Canada": "North America",
      "Cape Verde": "Africa",
      "Cayman Islands": "North America",
      "Central African Republic": "Africa",
      "Chad": "Africa",
      "Chile": "South America",
      "China": "Asia",
      "Christmas Island": "Oceania",
      "Cocos (Keeling) Islands": "Oceania",
      "Colombia": "South America",
      "Comoros": "Africa",
      "Congo": "Africa",
      "Congo, Democratic Republic of": "Africa",
      "Congo, Democratic Republic of the": "Africa",
      "Congo, Republic of the": "Africa",
      "Cook Islands": "Oceania",
      "Costa Rica": "North America",
      "Cote d'Ivoire": "Africa",
      "Croatia": "Europe",
      "Cuba": "North America",
      "Cyprus": "Europe",
      "Czech Republic": "Europe",
      "Denmark": "Europe",
      "Djibouti": "Africa",
      "Dominica": "North America",
      "Dominican Republic": "North America",
      "East Timor": "Asia",
      "Ecuador": "South America",
      "Egypt": "Africa",
      "El Salvador": "North America",
      "Equatorial Guinea": "Africa",
      "Eritrea": "Africa",
      "Estonia": "Europe",
      "Ethiopia": "Africa",
      "Falkland Islands (Islas Malvinas)": "South America",
      "Faroe Islands": "Oceania",
      "Fiji": "Oceania",
      "Finland": "Europe",
      "France": "Europe",
      "French Guiana": "South America",
      "French Polynesia": "Oceania",
      "French Southern and Antarctic Lands": "Oceania",
      "Gabon": "Africa",
      "Gambia": "Africa",
      "Gambia, The": "Africa",
      "Georgia": "Europe",
      "Germany": "Europe",
      "Ghana": "Africa",
      "Gibraltar": "Europe",
      "Greece": "Europe",
      "Greenland": "North America",
      "Grenada": "North America",
      "Guadeloupe": "North America",
      "Guam": "Oceania",
      "Guatemala": "North America",
      "Guernsey": "Europe",
      "Guinea": "Africa",
      "Guinea-Bissau": "Africa",
      "Guyana": "South America",
      "Haiti": "North America",
      "Heard Island and McDonald Islands": "Oceania",
      "Holy See (Vatican City)": "Europe",
      "Honduras": "North America",
      "Hong Kong": "Asia",
      "Hungary": "Europe",
      "Iceland": "Europe",
      "India": "Asia",
      "Indonesia": "Asia",
      "Iran": "Asia",
      "Iraq": "Asia",
      "Ireland": "Europe",
      "Isle of Man": "Europe",
      "Israel": "Asia",
      "Italy": "Europe",
      "Ivory Coast": "Africa",
      "Jamaica": "North America",
      "Japan": "Asia",
      "Jersey": "Europe",
      "Jordan": "Asia",
      "Kazakhstan": "Asia",
      "Kenya": "Africa",
      "Kiribati": "Oceania",
      "Korea, North": "Asia",
      "Korea, South": "Asia",
      "Kuwait": "Asia",
      "Kyrgyzstan": "Asia",
      "Laos": "Asia",
      "Latvia": "Europe",
      "Lebanon": "Asia",
      "Lesotho": "Africa",
      "Liberia": "Africa",
      "Libya": "Africa",
      "Liechtenstein": "Europe",
      "Lithuania": "Europe",
      "Luxembourg": "Europe",
      "Macau": "Asia",
      "Macedonia": "Europe",
      "Madagascar": "Africa",
      "Malawi": "Africa",
      "Malaysia": "Asia",
      "Maldives": "Asia",
      "Mali": "Africa",
      "Malta": "Europe",
      "Marshall Islands": "Oceania",
      "Martinique": "North America",
      "Mauritania": "Africa",
      "Mauritius": "Africa",
      "Mayotte": "Africa",
      "Mexico": "North America",
      "Micronesia": "Oceania",
      "Micronesia, Federated States of": "Oceania",
      "Moldova": "Europe",
      "Monaco": "Europe",
      "Mongolia": "Asia",
      "Montenegro": "Europe",
      "Montserrat": "North America",
      "Morocco": "Africa",
      "Mozambique": "Africa",
      "Namibia": "Africa",
      "Nauru": "Oceania",
      "Nepal": "Asia",
      "Netherlands": "Europe",
      "Netherlands Antilles": "North America",
      "New Caledonia": "Oceania",
      "New Zealand": "Oceania",
      "Nicaragua": "North America",
      "Niger": "Africa",
      "Nigeria": "Africa",
      "Niue": "Oceania",
      "Norfolk Island": "Oceania",
      "Northern Mariana Islands": "Oceania",
      "Norway": "Europe",
      "Oman": "Asia",
      "Pakistan": "Asia",
      "Palau": "Oceania",
      "Palestine": "Asia",
      "Panama": "North America",
      "Papua New Guinea": "Oceania",
      "Paraguay": "South America",
      "Peru": "South America",
      "Philippines": "Asia",
      "Pitcairn Islands": "Asia",
      "Poland": "Europe",
      "Portugal": "Europe",
      "Puerto Rico": "North America",
      "Qatar": "Asia",
      "Reunion": "Africa",
      "Romania": "Europe",
      "Russia": "Asia",
      "Russian Federation": "Asia",
      "Rwanda": "Africa",
      "Saint Barthelemy": "North America",
      "Saint Helena": "Africa",
      "Saint Kitts and Nevis": "North America",
      "Saint Lucia": "North America",
      "Saint Martin": "North America",
      "Saint Pierre and Miquelon": "North America",
      "Saint Vincent and the Grenadines": "North America",
      "Samoa": "Oceania",
      "San Marino": "Europe",
      "Sao Tome and Principe": "Africa",
      "Saudi Arabia": "Asia",
      "Senegal": "Africa",
      "Serbia": "Europe",
      "Seychelles": "Africa",
      "Sierra Leone": "Africa",
      "Singapore": "Asia",
      "Slovakia": "Europe",
      "Slovenia": "Europe",
      "Solomon Islands": "Oceania",
      "Somalia": "Africa",
      "South Africa": "Africa",
      "South Georgia South Sandwich Islands": "South America",
      "South Sudan": "Africa",
      "Spain": "Europe",
      "Sri Lanka": "Asia",
      "Sudan": "Africa",
      "Suriname": "South America",
      "Svalbard": "Europe",
      "Swaziland": "Africa",
      "Sweden": "Europe",
      "Switzerland": "Europe",
      "Syria": "Asia",
      "Taiwan": "Asia",
      "Tajikistan": "Asia",
      "Tanzania": "Africa",
      "Thailand": "Asia",
      "Timor-Leste": "Asia",
      "Togo": "Africa",
      "Tokelau": "Oceania",
      "Tonga": "Oceania",
      "Trinidad and Tobago": "North America",
      "Tunisia": "Africa",
      "Turkey": "Asia",
      "Turkmenistan": "Asia",
      "Turks and Caicos Islands": "North America",
      "Tuvalu": "Oceania",
      "Uganda": "Africa",
      "Ukraine": "Europe",
      "United Arab Emirates": "Asia",
      "United Kingdom": "Europe",
      "United States": "North America",
      "Uruguay": "South America",
      "Uzbekistan": "Asia",
      "Vanuatu": "Oceania",
      "Vatican City": "Europe",
      "Venezuela": "South America",
      "Vietnam": "Asia",
      "Virgin Islands": "North America",
      "Wallis and Futuna": "Oceania",
      "Western Sahara": "Africa",
      "Yemen": "Asia",
      "Zambia": "Africa",
      "Zimbabwe": "Africa"
    };

    const def = new Observable(observer => {
      this.performGetRequest('http://ip-api.com/json')
        .subscribe(
          (data: any) => {
            data.continent = countryToContinentMap[data.country];
            observer.next(data);
            observer.complete();
          },
          () => {
            observer.error();
          }
        );
    });

    return def;
  }

  countryCodeList():any {
    return {
      'AF': 'Afghanistan',
      'AL': 'Albania',
      'DZ': 'Algeria',
      'AS': 'American Samoa',
      'AD': 'Andorra',
      'AO': 'Angola',
      'AI': 'Anguilla',
      'AQ': 'Antarctica',
      'AG': 'Antigua and Barbuda',
      'AR': 'Argentina',
      'AM': 'Armenia',
      'AW': 'Aruba',
      'AU': 'Australia',
      'AT': 'Austria',
      'AZ': 'Azerbaijan',
      'BS': 'Bahamas',
      'BH': 'Bahrain',
      'BD': 'Bangladesh',
      'BB': 'Barbados',
      'BY': 'Belarus',
      'BE': 'Belgium',
      'BZ': 'Belize',
      'BJ': 'Benin',
      'BM': 'Bermuda',
      'BT': 'Bhutan',
      'BO': 'Bolivia',
      'BQ': 'Bonaire, Sint Eustatius, and Saba',
      'BA': 'Bosnia and Herzegovina',
      'BW': 'Botswana',
      'BV': 'Bouvet Island',
      'BR': 'Brazil',
      'IO': 'British Indian Ocean Territory',
      'BN': 'Brunei',
      'BG': 'Bulgaria',
      'BF': 'Burkina Faso',
      'BI': 'Burundi',
      'CV': 'Cabo Verde',
      'KH': 'Cambodia',
      'CM': 'Cameroon',
      'CA': 'Canada',
      'KY': 'Cayman Islands',
      'CF': 'Central African Republic',
      'TD': 'Chad',
      'CL': 'Chile',
      'CN': 'China',
      'CX': 'Christmas Island',
      'CC': 'Cocos (Keeling) Islands',
      'CO': 'Colombia',
      'KM': 'Comoros',
      'CG': 'Congo (Congo-Brazzaville)',
      'CD': 'Congo (Congo-Kinshasa)',
      'CK': 'Cook Islands',
      'CR': 'Costa Rica',
      'HR': 'Croatia',
      'CU': 'Cuba',
      'CW': 'Curaçao',
      'CY': 'Cyprus',
      'CZ': 'Czechia',
      'DK': 'Denmark',
      'DJ': 'Djibouti',
      'DM': 'Dominica',
      'DO': 'Dominican Republic',
      'EC': 'Ecuador',
      'EG': 'Egypt',
      'SV': 'El Salvador',
      'GQ': 'Equatorial Guinea',
      'ER': 'Eritrea',
      'EE': 'Estonia',
      'SZ': 'Eswatini',
      'ET': 'Ethiopia',
      'FK': 'Falkland Islands (Islas Malvinas)',
      'FO': 'Faroe Islands',
      'FJ': 'Fiji',
      'FI': 'Finland',
      'FR': 'France',
      'GF': 'French Guiana',
      'PF': 'French Polynesia',
      'TF': 'French Southern and Antarctic Lands',
      'GA': 'Gabon',
      'GM': 'Gambia',
      'GE': 'Georgia',
      'DE': 'Germany',
      'GH': 'Ghana',
      'GI': 'Gibraltar',
      'GR': 'Greece',
      'GL': 'Greenland',
      'GD': 'Grenada',
      'GP': 'Guadeloupe',
      'GU': 'Guam',
      'GT': 'Guatemala',
      'GG': 'Guernsey',
      'GN': 'Guinea',
      'GW': 'Guinea-Bissau',
      'GY': 'Guyana',
      'HT': 'Haiti',
      'HM': 'Heard Island and McDonald Islands',
      'HN': 'Honduras',
      'HK': 'Hong Kong',
      'HU': 'Hungary',
      'IS': 'Iceland',
      'IN': 'India',
      'ID': 'Indonesia',
      'IR': 'Iran',
      'IQ': 'Iraq',
      'IE': 'Ireland',
      'IM': 'Isle of Man',
      'IL': 'Israel',
      'IT': 'Italy',
      'CI': 'Ivory Coast',
      'JM': 'Jamaica',
      'JP': 'Japan',
      'JE': 'Jersey',
      'JO': 'Jordan',
      'KZ': 'Kazakhstan',
      'KE': 'Kenya',
      'KI': 'Kiribati',
      'KW': 'Kuwait',
      'KG': 'Kyrgyzstan',
      'LA': 'Laos',
      'LV': 'Latvia',
      'LB': 'Lebanon',
      'LS': 'Lesotho',
      'LR': 'Liberia',
      'LY': 'Libya',
      'LI': 'Liechtenstein',
      'LT': 'Lithuania',
      'LU': 'Luxembourg',
      'MO': 'Macao',
      'MG': 'Madagascar',
      'MW': 'Malawi',
      'MY': 'Malaysia',
      'MV': 'Maldives',
      'ML': 'Mali',
      'MT': 'Malta',
      'MH': 'Marshall Islands',
      'MQ': 'Martinique',
      'MR': 'Mauritania',
      'MU': 'Mauritius',
      'YT': 'Mayotte',
      'MX': 'Mexico',
      'FM': 'Micronesia',
      'MD': 'Moldova',
      'MC': 'Monaco',
      'MN': 'Mongolia',
      'ME': 'Montenegro',
      'MS': 'Montserrat',
      'MA': 'Morocco',
      'MZ': 'Mozambique',
      'MM': 'Myanmar (Burma)',
      'NA': 'Namibia',
      'NR': 'Nauru',
      'NP': 'Nepal',
      'NL': 'Netherlands',
      'NC': 'New Caledonia',
      'NZ': 'New Zealand',
      'NI': 'Nicaragua',
      'NE': 'Niger',
      'NG': 'Nigeria',
      'NU': 'Niue',
      'NF': 'Norfolk Island',
      'KP': 'North Korea',
      'MK': 'North Macedonia',
      'MP': 'Northern Mariana Islands',
      'NO': 'Norway',
      'OM': 'Oman',
      'PK': 'Pakistan',
      'PS': 'Palestine',
      'PA': 'Panama',
      'PG': 'Papua New Guinea',
      'PY': 'Paraguay',
      'PE': 'Peru',
      'PH': 'Philippines',
      'PN': 'Pitcairn Islands',
      'PL': 'Poland',
      'PT': 'Portugal',
      'PR': 'Puerto Rico',
      'QA': 'Qatar',
      'RE': 'Réunion',
      'RO': 'Romania',
      'RU': 'Russia',
      'RW': 'Rwanda',
      'BL': 'Saint Barthélemy',
      'SH': 'Saint Helena',
      'KN': 'Saint Kitts and Nevis',
      'LC': 'Saint Lucia',
      'MF': 'Saint Martin',
      'PM': 'Saint Pierre and Miquelon',
      'WS': 'Samoa',
      'SM': 'San Marino',
      'ST': 'São Tomé and Príncipe',
      'SA': 'Saudi Arabia',
      'SN': 'Senegal',
      'RS': 'Serbia',
      'SC': 'Seychelles',
      'SL': 'Sierra Leone',
      'SG': 'Singapore',
      'SX': 'Sint Maarten',
      'SK': 'Slovakia',
      'SI': 'Slovenia',
      'SB': 'Solomon Islands',
      'SO': 'Somalia',
      'ZA': 'South Africa',
      'GS': 'South Georgia & South Sandwich Islands',
      'KR': 'South Korea',
      'SS': 'South Sudan',
      'ES': 'Spain',
      'LK': 'Sri Lanka',
      'VC': 'St. Vincent & Grenadines',
      'SD': 'Sudan',
      'SR': 'Suriname',
      'SJ': 'Svalbard and Jan Mayen',
      'SE': 'Sweden',
      'CH': 'Switzerland',
      'SY': 'Syria',
      'TW': 'Taiwan',
      'TJ': 'Tajikistan',
      'TZ': 'Tanzania',
      'TH': 'Thailand',
      'TL': 'Timor-Leste',
      'TG': 'Togo',
      'TK': 'Tokelau',
      'TO': 'Tonga',
      'TT': 'Trinidad and Tobago',
      'TN': 'Tunisia',
      'TR': 'Turkey',
      'TM': 'Turkmenistan',
      'TC': 'Turks and Caicos Islands',
      'TV': 'Tuvalu',
      'UG': 'Uganda',
      'UA': 'Ukraine',
      'AE': 'United Arab Emirates',
      'GB': 'United Kingdom',
      'US': 'United States',
      'UY': 'Uruguay',
      'UM': 'U.S. Outlying Islands',
      'VI': 'U.S. Virgin Islands',
      'UZ': 'Uzbekistan',
      'VU': 'Vanuatu',
      'VA': 'Vatican City',
      'VE': 'Venezuela',
      'VN': 'Vietnam',
      'WF': 'Wallis and Futuna',
      'EH': 'Western Sahara',
      'YE': 'Yemen',
      'ZM': 'Zambia',
      'ZW': 'Zimbabwe',
    };
  }

  euCountryList():any {
    return {
      'AT': 'Austria',
      'BE': 'Belgium',
      'BG': 'Bulgaria',
      'CY': 'Cyprus',
      'CZ': 'Czechia',
      'DE': 'Germany',
      'DK': 'Denmark',
      'EE': 'Estonia',
      'ES': 'Spain',
      'FI': 'Finland',
      'FR': 'France',
      'GR': 'Greece',
      'HR': 'Croatia',
      'HU': 'Hungary',
      'IE': 'Ireland',
      'IT': 'Italy',
      'LT': 'Lithuania',
      'LU': 'Luxembourg',
      'LV': 'Latvia',
      'MT': 'Malta',
      'NL': 'Netherlands',
      'PL': 'Poland',
      'PT': 'Portugal',
      'RO': 'Romania',
      'SE': 'Sweden',
      'SI': 'Slovenia',
      'SK': 'Slovakia'
    };
  }

}
